Update onboarding images
Rebeccompany/Project-Swift pull request #344
Opened 2022-10-26 20:05 UTC by claudia1402

mudança de assets da spixi com light e dark mode sem sombra, além dos de flashcards, baralhos e coleções. Swiftlint para navigationstack e mudança de cor de fundo dos onboarding's

2022-10-26 20:43 UTC, gbrlCM requested changes

2022-10-26 20:43 UTC, gbrlCM commented on Bird-Modules/Sources/HummingBird/Images.swift
> -        Image("FotoOnboarding", bundle: .module)
O padrão de nomenclatura é inglês.

2022-10-26 20:43 UTC, gbrlCM commented on Bird-Modules/Sources/OnboardingFeature/OnboardingPageFourView.swift
>                          .padding(.top)
pode substituir os baddings top e bottom por vertical.

2022-10-26 20:43 UTC, gbrlCM commented on Bird-Modules/Sources/StudyFeature/DifficultyStep.swift
> +            generator.notificationOccurred(.success)
A gente quer que a pessoa tenha um feedback de sucesso quando ela acha muito difícil?

2022-10-26 22:31 UTC, MarcosChevis approved these changes

2022-10-27 19:56 UTC, gbrlCM approved these changes

2022-10-27 19:56 UTC, merged