Feat/sessões para hoje
Rebeccompany/Project-Swift pull request #383
Opened 2022-11-17 20:43 UTC by caroltaus

Implementação da funcionalidade sessões para hoje e refatoração de mocks

2022-11-18 14:43 UTC, rebeccamello requested changes

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/ContentViewModel.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/DeckForTodayCell.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/DeckForTodayCell.swift
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/DeckGridView.swift
> -                    .buttonStyle(DeckCell.Style(color: deck.color))
Isso foi removido errado

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/DeckGridView.swift
>                          Button(NSLocalizedString("deletar", bundle: .module, comment: ""), role: .destructive) {
Identação errada

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/DetailView.swift
> +        VStack(alignment: .leading) {
Precisa estar em uma VStack?

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/SessionsForTodayView.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/SessionsForTodayView.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/SessionsForTodayView.swift
> +
Tirar varias linhas

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/SessionsForTodayView.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/AppFeature/Detail/SessionsForTodayView.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/DeckFeature/DeckViewModel.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/StudyFeature/StudyViewModel.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/StudyFeature/StudyViewModel.swift
>      init() {
Precisa desse init?

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/StudyFeature/StudyViewModel.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Sources/StudyFeature/StudyViewModel.swift
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Tests/DeckFeatureTests/DeckViewModelTests.swift
> +    var deck0: Deck!
Melhorar o nome desses decks

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Tests/DeckFeatureTests/DeckViewModelTests.swift
> +    enum WoodpeckerState {
Não colocar no meio do arquivo

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Tests/ImportingFeatureTests/ImportViewModelTest.swift
> +    enum WoodpeckerState {
Não colocar no meio do arquivo

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Tests/NewDeckFeatureTests/NewDeckViewModelTests.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Tests/NewDeckFeatureTests/NewDeckViewModelTests.swift
> +    enum WoodpeckerState {
Não colocar no meio do arquivo

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Tests/NewFlashcardFeatureTests/NewFlashcardFeatureTests.swift
> +
Tirar linha

2022-11-18 14:43 UTC, rebeccamello commented on Bird-Modules/Tests/NewFlashcardFeatureTests/NewFlashcardFeatureTests.swift
> +    enum WoodpeckerState {
Não colocar no meio do arquivo

2022-11-18 19:53 UTC, caroltaus commented on Bird-Modules/Sources/AppFeature/Detail/DetailView.swift
> +        VStack(alignment: .leading) {
no :) tirei

2022-11-18 20:31 UTC, caroltaus commented on Bird-Modules/Sources/StudyFeature/StudyViewModel.swift
>      init() {
achávamos que sim pq é classe, mas roda normal sem então tirei.

2022-11-21 18:29 UTC, rebeccamello approved these changes

2022-11-21 18:29 UTC, merged