Feat/classkit structure
Rebeccompany/Project-Swift pull request #397
Opened 2022-11-24 03:20 UTC by MarcosChevis

2022-11-24 17:35 UTC, rebeccamello requested changes

2022-11-24 17:35 UTC, rebeccamello commented on Bird-Modules/Sources/ClassKitFeature/CLSContext+identifierPath.swift
> +//  File.swift
Nome do arquivo

2022-11-24 17:35 UTC, rebeccamello commented on Bird-Modules/Sources/ClassKitFeature/CLSDeckLibrary.swift
> +//  File.swift
Nome do arquivo

2022-11-24 17:35 UTC, rebeccamello commented on Bird-Modules/Sources/ClassKitFeature/CLSDeckLibrary.swift
> +
Tirar linha

2022-11-24 17:35 UTC, rebeccamello commented on Bird-Modules/Sources/ClassKitFeature/CLSDeckLibrary.swift
> +
Tirar linha

2022-11-24 17:35 UTC, rebeccamello commented on Bird-Modules/Sources/ClassKitFeature/Deck+Node.swift
> +//  File.swift
Nome do arquivo

2022-11-24 17:35 UTC, rebeccamello commented on Bird-Modules/Sources/ClassKitFeature/Node.swift
> +//  File.swift
Nome do arquivo

2022-11-28 19:27 UTC, gbrlCM requested changes

2022-11-28 19:27 UTC, gbrlCM commented on Bird-Modules/Sources/AppFeature/Navigation/AppRouter.swift
> +    func onOpen(url: URL) {
Testes?

2022-11-29 18:32 UTC, gbrlCM approved these changes

2022-11-29 18:33 UTC, rebeccamello approved these changes

2022-11-29 18:51 UTC, merged